#!/usr/bin/env python3
"""Generate the E. coli codon usage table from the K-12 MG1655 genome.

    python3 Tools/data/generate_codon_table.py

Writes `Packages/BoffinCore/Sources/BoffinCore/Generated/CodonTable.swift`.

Why this is computed rather than copied
---------------------------------------
The obvious source is a published codon usage table, and the obvious one of
those is Kazusa. Its entry for *Escherichia coli* K12 (species 83333) is built
on **14 CDS and 5,122 codons**. That is a fine sample of fourteen genes and a
poor description of the organism, and it is exactly the plausible-but-wrong
artefact that a table gets to be once it is quoted: it carries an authoritative
name and no visible N.

So the table is computed from every annotated coding sequence in the reference
genome, U00096.3, fetched from NCBI. That is 4,318 CDS and roughly 1.3 million
codons, and the count is printed and recorded so the next person can see what
the numbers rest on.

The genome is a public reference sequence; the codon counts derived from it are
measurements of it. Provenance goes in `Datasets/MANIFEST.md` along with the
checksum of what was downloaded.
"""

from __future__ import annotations

import hashlib
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "Packages/BoffinCore/Sources/BoffinCore/Generated/CodonTable.swift"
CACHE = ROOT / "Datasets/codon/ecoli_cds.fna"

ACCESSION = "U00096.3"
SOURCE = (
    "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
    f"?db=nuccore&id={ACCESSION}&rettype=fasta_cds_na&retmode=text"
)

# The standard genetic code, table 1. Written out because it is the definition
# of the mapping rather than a measurement of anything, and because deriving it
# would need another download to check it against.
CODE = {
    "TTT": "F", "TTC": "F", "TTA": "L", "TTG": "L",
    "CTT": "L", "CTC": "L", "CTA": "L", "CTG": "L",
    "ATT": "I", "ATC": "I", "ATA": "I", "ATG": "M",
    "GTT": "V", "GTC": "V", "GTA": "V", "GTG": "V",
    "TCT": "S", "TCC": "S", "TCA": "S", "TCG": "S",
    "CCT": "P", "CCC": "P", "CCA": "P", "CCG": "P",
    "ACT": "T", "ACC": "T", "ACA": "T", "ACG": "T",
    "GCT": "A", "GCC": "A", "GCA": "A", "GCG": "A",
    "TAT": "Y", "TAC": "Y", "TAA": "*", "TAG": "*",
    "CAT": "H", "CAC": "H", "CAA": "Q", "CAG": "Q",
    "AAT": "N", "AAC": "N", "AAA": "K", "AAG": "K",
    "GAT": "D", "GAC": "D", "GAA": "E", "GAG": "E",
    "TGT": "C", "TGC": "C", "TGA": "*", "TGG": "W",
    "CGT": "R", "CGC": "R", "CGA": "R", "CGG": "R",
    "AGT": "S", "AGC": "S", "AGA": "R", "AGG": "R",
    "GGT": "G", "GGC": "G", "GGA": "G", "GGG": "G",
}


def fetch() -> str:
    if CACHE.exists():
        return CACHE.read_text()
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(SOURCE, timeout=300) as response:
        text = response.read().decode("ascii")
    CACHE.write_text(text)
    return text


def main() -> int:
    text = fetch()
    digest = hashlib.sha256(text.encode()).hexdigest()

    counts: Counter[str] = Counter()
    sequences = 0
    skipped = 0
    current: list[str] = []

    def consume(parts: list[str]) -> None:
        nonlocal sequences, skipped
        sequence = "".join(parts).upper()
        if not sequence:
            return
        # A CDS whose length is not a multiple of three is annotated across a
        # frameshift or a sequencing gap. Counting it would slide every codon
        # after the break by one, so it is dropped and the count reported.
        if len(sequence) % 3 or any(base not in "ACGT" for base in sequence):
            skipped += 1
            return
        sequences += 1
        for index in range(0, len(sequence), 3):
            counts[sequence[index : index + 3]] += 1

    for line in text.splitlines():
        if line.startswith(">"):
            consume(current)
            current = []
        else:
            current.append(line.strip())
    consume(current)

    total = sum(counts.values())
    print(f"{sequences:,} coding sequences, {total:,} codons "
          f"({skipped:,} skipped for length or ambiguity)")

    byAcid: dict[str, list[tuple[str, int]]] = defaultdict(list)
    for codon, acid in CODE.items():
        byAcid[acid].append((codon, counts.get(codon, 0)))

    lines: list[str] = []
    lines.append("//  CodonTable.swift")
    lines.append("//  BoffinCore")
    lines.append("//")
    lines.append("//  GENERATED by Tools/data/generate_codon_table.py. Do not edit.")
    lines.append("//")
    lines.append(f"//  Escherichia coli K-12 MG1655, {ACCESSION}, every annotated CDS:")
    lines.append(f"//  {sequences:,} sequences and {total:,} codons.")
    lines.append("//")
    lines.append("//  Computed rather than copied. Kazusa's table for this organism is")
    lines.append("//  built on 14 CDS and 5,122 codons, which is a fine sample of")
    lines.append("//  fourteen genes and a poor description of the organism.")
    lines.append(f"//  SHA-256 of the downloaded CDS set: {digest[:32]}...")
    lines.append("")
    lines.append("public enum CodonTable {")
    lines.append("")
    lines.append(f'    /// What the frequencies were measured on.')
    lines.append(f'    public static let provenance =')
    lines.append(
        f'        "Escherichia coli K-12 MG1655 ({ACCESSION}), {sequences:,} coding '
        f'sequences, {total:,} codons"')
    lines.append("")
    lines.append("    /// Codons for each amino acid, most frequent first, with the")
    lines.append("    /// fraction of that amino acid's codons each one accounts for.")
    lines.append("    public static let byAminoAcid: [Character: [(codon: String, fraction: Double)]] = [")
    for acid in sorted(byAcid):
        if acid == "*":
            continue
        entries = sorted(byAcid[acid], key=lambda pair: -pair[1])
        acidTotal = sum(count for _, count in entries) or 1
        rendered = ", ".join(
            f'(codon: "{codon}", fraction: {count / acidTotal:.4f})'
            for codon, count in entries)
        lines.append(f'        "{acid}": [{rendered}],')
    lines.append("    ]")
    lines.append("")
    stops = sorted(byAcid["*"], key=lambda pair: -pair[1])
    stopTotal = sum(count for _, count in stops) or 1
    lines.append("    /// Stop codons, most frequent first.")
    lines.append("    public static let stopCodons: [(codon: String, fraction: Double)] = [")
    lines.append(
        "        "
        + ", ".join(
            f'(codon: "{codon}", fraction: {count / stopTotal:.4f})'
            for codon, count in stops))
    lines.append("    ]")
    lines.append("}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
