//  EmbeddingEngineTests.swift
//  BoffinMLTests
//
//  Cross-language parity. BoffinML's other tests prove the tiler is
//  self-consistent, but self-consistency is exactly what a wrong tokeniser also
//  has: encode every residue one index off and the pipeline runs perfectly,
//  caches happily, and returns embeddings for a different protein. The only way
//  to catch that is to compare against the reference implementation, so these
//  tests assert against a golden file exported from PyTorch by
//  `Tools/coreml/export_golden.py`.
//
//  The model is a build artefact and is not committed (67 MB, regenerated by
//  `Tools/coreml/convert_backbone.py`). When it is absent these tests report
//  why and skip, rather than silently passing and creating the impression the
//  engine has been checked.

import BoffinCore
import Foundation
import Testing

@testable import BoffinML

private var repositoryRoot: URL {
    URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()  // BoffinMLTests
        .deletingLastPathComponent()  // Tests
        .deletingLastPathComponent()  // BoffinML
        .deletingLastPathComponent()  // Packages
        .deletingLastPathComponent()  // root
}

private let modelName = "esm2_t12_35M_UR50D"
private var modelURL: URL { repositoryRoot.appending(path: "Models/\(modelName).mlpackage") }
private var tokeniserURL: URL {
    repositoryRoot.appending(path: "Models/\(modelName).tokeniser.json")
}
private var goldenURL: URL {
    repositoryRoot.appending(path: "Fixtures/expected/\(modelName).golden.json")
}

private struct Golden: Decodable {
    let sequence: String
    let residueCount: Int
    let width: Int
    let pooled: [Double]
    let firstResidue: [Double]
    let lastResidue: [Double]

    enum CodingKeys: String, CodingKey {
        case sequence
        case residueCount = "residue_count"
        case width
        case pooled
        case firstResidue = "first_residue"
        case lastResidue = "last_residue"
    }
}

private func loadGolden() throws -> Golden {
    try JSONDecoder().decode(Golden.self, from: Data(contentsOf: goldenURL))
}

/// The converted model is not committed. Skip rather than fail when it is not
/// present, but say so loudly enough that a skipped run is not mistaken for a
/// passing one.
private var modelIsAvailable: Bool {
    FileManager.default.fileExists(atPath: modelURL.path)
        && FileManager.default.fileExists(atPath: tokeniserURL.path)
}

/// fp16 on the Neural Engine agrees with PyTorch fp32 to roughly 1% of signal
/// scale, which is the revised parity gate. Comparing to more digits than the
/// hardware can represent would be a test that fails for being right.
private let relativeTolerance = 0.02

@Suite("Tokeniser")
struct TokeniserTests {

    @Test("The exported alphabet round-trips residues to indices")
    func alphabetRoundTrips() throws {
        try #require(modelIsAvailable, "converted model not present: run convert_backbone.py")
        let tokeniser = try Tokeniser(contentsOf: tokeniserURL)

        // ESM-2's alphabet is 33 tokens. If this changed, the model changed.
        #expect(tokeniser.tokens.count == 33)
        #expect(tokeniser.prependBOS)
        #expect(tokeniser.appendEOS)
        #expect(tokeniser.specialTokenCount == 2)
    }

    @Test("Non-canonical residues map to unknown, never to a neighbour")
    func nonCanonicalMapsToUnknown() throws {
        try #require(modelIsAvailable, "converted model not present")
        let tokeniser = try Tokeniser(contentsOf: tokeniserURL)
        // Dropping them instead would shift every downstream residue by one and
        // silently misalign every track against the sequence.
        let index = tokeniser.index(for: ResidueIdentity(code: "\u{00DF}"))
        #expect(index == tokeniser.unknownIndex)
    }

    @Test("Encoding wraps residues in the special tokens and pads the rest")
    func encodingWrapsAndPads() throws {
        try #require(modelIsAvailable, "converted model not present")
        let tokeniser = try Tokeniser(contentsOf: tokeniserURL)
        let sequence = ProteinSequence(name: "t", letters: "MKVL", source: .pasted)

        let (tokens, range) = tokeniser.encode(sequence.residues, paddedTo: 128)
        #expect(tokens.count == 128)
        #expect(tokens[0] == tokeniser.clsIndex)
        #expect(range == 1..<5)
        #expect(tokens[5] == tokeniser.eosIndex)
        #expect(tokens[6...].allSatisfy { $0 == tokeniser.paddingIndex })
    }
}

@Suite("Embedding engine, against the PyTorch golden")
struct EmbeddingEngineTests {

    @Test("Ubiquitin embeds to the reference vectors")
    func ubiquitinMatchesGolden() async throws {
        try #require(modelIsAvailable, "converted model not present: run convert_backbone.py")
        let golden = try loadGolden()

        let engine = try EmbeddingEngine(modelURL: modelURL, tokeniserURL: tokeniserURL)
        let sequence = ProteinSequence(
            name: "ubiquitin", letters: golden.sequence, source: .fixture(name: "1UBQ"))
        let result = try await engine.embed(sequence)

        #expect(result.hiddenStates.count == golden.residueCount)
        #expect(result.width == golden.width)
        #expect(result.passes == 1)

        // Compared relative to the signal's own scale: an absolute tolerance is
        // only meaningful once you know how large the activations are.
        func agrees(_ actual: [Float], _ expected: [Double], _ label: String) {
            let scale = expected.map(abs).max() ?? 1
            var worst = 0.0
            for (a, e) in zip(actual, expected) { worst = max(worst, abs(Double(a) - e)) }
            #expect(
                worst / scale < relativeTolerance,
                "\(label): worst relative difference \(worst / scale)")
        }

        agrees(result.pooled, golden.pooled, "pooled embedding")
        agrees(result.hiddenStates[0], golden.firstResidue, "first residue")
        agrees(
            result.hiddenStates[golden.residueCount - 1], golden.lastResidue, "last residue")
    }

    @Test("The pooled embedding is the mean over real residues only")
    func pooledExcludesSpecialTokens() async throws {
        try #require(modelIsAvailable, "converted model not present")
        let golden = try loadGolden()
        let engine = try EmbeddingEngine(modelURL: modelURL, tokeniserURL: tokeniserURL)
        let sequence = ProteinSequence(
            name: "t", letters: golden.sequence, source: .pasted)
        let result = try await engine.embed(sequence)

        // Recompute the mean from the returned rows: if pooling had included
        // <cls>, <eos> or padding, these would not agree.
        var manual = [Float](repeating: 0, count: result.width)
        for row in result.hiddenStates {
            for i in 0..<result.width { manual[i] += row[i] }
        }
        for i in 0..<result.width { manual[i] /= Float(result.hiddenStates.count) }

        var worst: Float = 0
        for (a, b) in zip(result.pooled, manual) { worst = max(worst, abs(a - b)) }
        #expect(worst < 1e-4)
    }

    @Test("Embedding is deterministic across engine instances")
    func embeddingIsDeterministic() async throws {
        try #require(modelIsAvailable, "converted model not present")

        // Two engines, so the cache cannot be what makes these agree. Core ML
        // reusing a stale compiled model, or the tokeniser depending on
        // anything other than its input, would show up here.
        let letters = String(repeating: "MQIFVKTLTG", count: 8)
        let sequence = ProteinSequence(name: "t", letters: letters, source: .pasted)

        let first = try await EmbeddingEngine(modelURL: modelURL, tokeniserURL: tokeniserURL)
            .embed(sequence)
        let second = try await EmbeddingEngine(modelURL: modelURL, tokeniserURL: tokeniserURL)
            .embed(sequence)

        #expect(first.pooled == second.pooled)
        #expect(first.hiddenStates.count == second.hiddenStates.count)
    }

    // Note on a test that is deliberately NOT here: comparing residue N of a
    // short sequence against residue N of a longer one that starts with it.
    // That looks like a padding-invariance check and is not one. ESM-2 is
    // bidirectional, so residue 40 of a 100-mer sees 60 residues of downstream
    // context and residue 40 of a 300-mer sees 260: the embeddings SHOULD
    // differ, and here did so by 24%. Padding invariance is a statement about
    // the same residues in different BUCKETS, which the Core ML parity gate
    // checks directly (Tools/coreml/validate_parity.py, bucket 128 versus 512,
    // 0.37% relative). Asserting it at this level would only have been testing
    // the language model's context sensitivity and calling it a bug.

    @Test("Repeating a sequence is served from cache")
    func repeatIsCached() async throws {
        try #require(modelIsAvailable, "converted model not present")
        let engine = try EmbeddingEngine(modelURL: modelURL, tokeniserURL: tokeniserURL)
        let sequence = ProteinSequence(name: "t", letters: "MQIFVKTLTGKTITLE", source: .pasted)

        let first = try await engine.embed(sequence)
        let second = try await engine.embed(sequence)
        #expect(first.pooled == second.pooled)
    }

    @Test("An empty sequence is refused rather than embedded")
    func emptySequenceIsRefused() async throws {
        try #require(modelIsAvailable, "converted model not present")
        let engine = try EmbeddingEngine(modelURL: modelURL, tokeniserURL: tokeniserURL)
        let empty = ProteinSequence(name: "t", letters: "", source: .pasted)
        await #expect(throws: EmbeddingError.self) { try await engine.embed(empty) }
    }
}
